defaults:
  baud_rate: 4800
  use_fahrenheit: true
  follow_me_timeout: 7200
  log_rs485_comms: true

globals: !include src/globals.yaml

uart: !include src/uart.yaml

interval: !include src/intervals.yaml

sensor: !include src/sensors.yaml

binary_sensor: !include src/binary_sensors.yaml

text_sensor: !include src/text_sensors.yaml

select: !include src/selects.yaml

switch: !include src/switches.yaml

number: !include src/numbers.yaml
