- platform: template
  name: "send button"
  id: "send_button"
  internal: true
  on_press: 
    - uart.write: !lambda |-
        static std::vector<uint8_t> sendData = {0xaa, 0xc3, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x00, 0x55};
        sendData[6] = id(op_bytes);
        sendData[7] = id(fan_bytes);
        if (id(use_fahrenheit)) {
          sendData[8] = id(set_temp) + 0x87;
        } else {
          sendData[8] = id(set_temp);
        }

        sendData[9] = id(mode_flag_bytes);
        ESP_LOGI("custom","Getting ready to send: op %02X fan %02X temp %02X",id(op_bytes),id(fan_bytes),id(set_temp));
        uint8_t i=0;
        uint32_t crc=0;
        int len=16;
        for(i=0;i<len;i++)
        { 
          if(i!=14)
          {
            crc+=sendData[i];
          }
        }
        ESP_LOGI("custom","sum of values for CRC calc is %i",crc);
        sendData[14] = 0xFF - (crc&0xFF);
        ESP_LOGI("custom","calculated CRC is %x",crc);
        return sendData;