- platform: template
  id: set_temp
  name: "Set Point"
  step: 0.5
  mode: box
  min_value: "${60 if use_fahrenheit == true else 16}"
  max_value: "${86 if use_fahrenheit == true else 30}"
  unit_of_measurement: "${'°F' if use_fahrenheit == true else '°C'}"
  device_class: temperature
  optimistic: true
  set_action:
    - lambda: |-
        if (id(fetched_initial_state)) {
          id(new_input) = true;
        }

- platform: template
  id: follow_me_temp
  name: "Follow Me Temp"
  step: 0.01
  mode: box
  min_value: 0
  max_value: 100
  unit_of_measurement: "°C"
  device_class: temperature
  optimistic: true
  restore_value: true
  set_action:
    - lambda: |-
        id(last_follow_me_update) = static_cast<uint32_t>(id(uptime_sensor).state);
