- platform: template
  id: op_mode
  name: "Operating Mode"
  options:
    - "off"
    - auto
    - cool
    - dry
    - heat
    - fan_only
  initial_option: "off"
  optimistic: true
  set_action:
    - lambda: |-
        id(new_input) = true;

        // Changing mode invalidates follow me
        id(unit_follow_me_init) = false;

- platform: template
  id: fan_mode
  name: "Fan Mode"
  options:
    - low
    - medium
    - high
    - auto
  initial_option: auto
  optimistic: true
  set_action:
    - lambda: |-
        id(new_input) = true;

- platform: template
  id: preset_mode
  name: "Preset Mode"
  options:
    - none
    - sleep
    - boost
  initial_option: none
  optimistic: true
  set_action:
    - lambda: |-
        id(new_input) = true;
