# internal temp of esp device
- platform: internal_temperature
  name: "Internal Temperature"
  unit_of_measurement: "°C"
  device_class: temperature
  state_class: measurement

- platform: uptime
  id: uptime_sensor
  name: "Uptime Sensor"
  type: seconds
  update_interval: 1s
  internal: true

- platform: template
  id: t1_temp
  name: "T1 Room Temp"
  unit_of_measurement: "°C"
  device_class: temperature
  state_class: measurement

# Indoor coil. A appears to be the temp prior to air passing over the coil while B is the temp before  
- platform: template
  id: t2a_temp
  name: "T2A Indoor Coil Temp A"
  unit_of_measurement: "°C"
  device_class: temperature
  state_class: measurement

- platform: template
  id: t2b_temp
  name: "T2B Indoor Coil Temp B"
  unit_of_measurement: "°C"
  device_class: temperature
  state_class: measurement

- platform: template
  id: t3_temp
  name: "T3 Outdoor Coil Temp"
  unit_of_measurement: "°C"
  device_class: temperature
  state_class: measurement

- platform: template
  id: t4_temp
  name: "T4 Outdoor Temp"
  unit_of_measurement: "°C"
  device_class: temperature
  state_class: measurement

- platform: template
  id: t5_temp
  name: "T5 Compressor Discharge Temp"
  unit_of_measurement: "°C"
  device_class: temperature
  state_class: measurement

- platform: template
  id: current
  name: "Current"
  unit_of_measurement: "A"
  device_class: current
  state_class: measurement
  # This appears to be correlated with the activity of the indoor unit,
  # but it doesn't match the current reported by the device in inquiry mode
  # (nor does it seem to be a multiple of it), so disable it by default.
  disabled_by_default: true

- platform: template
  id: error_flags
  name: "Error Flags"
  state_class: measurement
  entity_category: diagnostic

- platform: template
  id: protect_flags
  name: "Protect Flags"
  state_class: measurement
  entity_category: diagnostic
