- platform: template
  id: vertical_swing
  name: "Vertical Swing"
  optimistic: true
  turn_on_action:
    - lambda: |-
        if (id(fetched_initial_state)) {
          id(new_input) = true;
        }
  turn_off_action:
    - lambda: |-
        if (id(fetched_initial_state)) {
          id(new_input) = true;
        }

- platform: template
  id: follow_me
  name: "Follow Me"
  optimistic: true
  restore_mode: RESTORE_DEFAULT_OFF
