# the 2 error code registers combined in one message. it's just the code number,
# you will need the service manual to decode them probably. I haven't tested any error
# codes yet. 
- platform: template
  id: error_codes
  name: "Error Codes"

- platform: template
  id: op_mode_detailed
  name: "Detailed Operating Mode"

- platform: template
  id: fan_mode_detailed
  name: "Detailed Fan Mode"
